// The only place for constants (AGENTS.md section 0.1). Each one says what it is and where it comes from.

/** Bitget public REST base URL. Source: https://www.bitget.com/api-doc/common/intro */
export const BITGET_BASE_URL = "https://api.bitget.com";

/** Bitget endpoint paths used by Morrow. Source: AGENTS.md section 3, confirmed in docs/VERIFIED.md. */
export const BITGET_PATHS = {
  loanCoins: "/api/v3/loan/coins",
  instruments: "/api/v3/market/instruments",
  tickers: "/api/v2/spot/market/tickers",
  historyCandles: "/api/v2/spot/market/history-candles",
  candles: "/api/v2/spot/market/candles",
  orderBook: "/api/v2/spot/market/orderbook",
  announcements: "/api/v2/public/annoucements", // Bitget's own spelling
} as const;

/** Unit conversions: true constants. */
export const MS_PER_SECOND = 1000;
export const SECONDS_PER_HOUR = 3600;
export const MS_PER_HOUR = SECONDS_PER_HOUR * MS_PER_SECOND;
export const MS_PER_DAY = 24 * MS_PER_HOUR;

/** Candle size used for reopen history. Source: Bitget candle granularity "1h" (AGENTS.md section 3). */
export const HISTORY_GRANULARITY = "1h";

/** Percent-to-ratio divisor: true constant. */
export const PERCENT = 100;

/**
 * Planning percentiles for the reopen drop (AGENTS.md section 4: "95th and 99th percentile drops").
 * These are policy choices from the product brief, not market data.
 */
export const PLANNING_PERCENTILES = { likely: 95, severe: 99 } as const;

/**
 * Default safety buffer below the margin-call level, in loan-health points.
 * Source: AGENTS.md section 4 ("10 points below the margin-call level"). The user can change it in Settings.
 * The margin-call level itself is always read live from Bitget.
 */
export const DEFAULT_TARGET_BUFFER_POINTS = 10;

/**
 * Default price-trust thresholds. Policy values chosen by the product, changeable per deployment.
 * They are not market data: the data they are compared with is always live.
 */
export const DEFAULT_TRUST_THRESHOLDS = {
  /** A last trade older than this many seconds is stale. */
  maxTradeAgeSeconds: 300,
  /** Spread (ask - bid) / mid above this ratio is too wide. */
  maxSpreadRatio: 0.01,
  /** Depth is counted within this ratio of the mid price on each side. */
  depthBandRatio: 0.01,
  /** Depth near the mid must be at least this multiple of the loan's backing value in quote coin. */
  minDepthToBackingRatio: 1,
  /** A move from last close bigger than this multiple of the stock's largest observed reopen gap is not trusted. */
  maxMoveVsHistoryMultiple: 1.5,
} as const;

/** Minimum number of past closures needed before a reopen history is used. Policy value. */
export const MIN_CLOSURES_FOR_HISTORY = 20;

/** Minutes after the US open before a promise is graded. Source: AGENTS.md section 6. */
export const GRADE_DELAY_MINUTES = 30;

import featuredClosureFile from "./featured-closure.json";
import nyseCalendarFile from "./nyse-calendar.json";

/**
 * The simulated loan behind "Watch a weekend" and the shadow ledger. These are scenario choices, not market data, and every
 * result built from them is labelled simulated. Loan health at the start is placed between the LIVE start level and the
 * LIVE margin-call level read from Bitget, so no limit is typed in here.
 */
export const SIMULATION = {
  /** Backing value of each simulated loan in USDT (the same size the history replay uses, docs/METHOD.md). */
  backingValueUsdt: 10_000,
  /** Idle USDT the simulated user holds, as a share of the debt (the replay's main setting). */
  idleShareOfDebt: 0.25,
  /** Start positions of the shadow ledger's loans: 0 is the live start level, 1 is the live margin-call level. */
  shadowStartPositions: [0, 0.5, 0.9],
  /** Start position of the loan shown in "Watch a weekend": halfway, close enough to matter, not already past the trigger. */
  watchStartPosition: 0.5,
  /** How many stock tokens the shadow ledger follows (the most traded ones, read live). */
  shadowTokens: 5,
} as const;

/** One stock token's biggest real gap down at a reopen, found by scripts/replay/src/featured.ts from Bitget hourly candles. */
export interface FeaturedClosure {
  coin: string;
  symbol: string;
  closeTs: number;
  reopenTs: number;
  /** Reopen price divided by the last close, minus one. */
  move: number;
}
export interface FeaturedClosureFile {
  source?: string;
  generatedAt?: string;
  featured: FeaturedClosure | null;
}
export const FEATURED_CLOSURE: FeaturedClosureFile = featuredClosureFile as FeaturedClosureFile;

/**
 * NYSE holidays, early closes and hours. Generated by tools/fetch-nyse-calendar.mjs from the official NYSE page
 * (source and fetch date are inside the file). Never edited by hand. The worker re-checks it on a schedule.
 */
export interface MarketCalendar {
  source: string;
  fetchedAt: string;
  timezone: string;
  years: number[];
  holidays: Array<{ date: string; name: string }>;
  earlyCloses: Array<{ date: string }>;
  coreOpen: string;
  coreClose: string;
  earlyCloseTime: string;
}
export const NYSE_CALENDAR: MarketCalendar = nyseCalendarFile;

/**
 * A stock token counts as trading through a closure when at least this share of the closure's hours have trades.
 * Stock tokens also trade extended hours around a closure, so one candle is not enough. Policy value; see docs/VERIFIED.md item 6.
 */
export const WEEKEND_TRADING_MIN_COVERAGE = 0.5;

/**
 * Worker schedule. Policy values chosen by the product (AGENTS.md section 13, step 5: "more often near a market closure").
 */
export const SCHEDULE = {
  /** Seconds between checks on an ordinary trading day. */
  normalPollSeconds: 300,
  /** Seconds between checks from this many hours before a closure until its reopen. */
  nearClosurePollSeconds: 60,
  nearClosureHours: 3,
  /** The weekly promise is written and sealed this many minutes before the closure starts. */
  promiseLeadMinutes: 60,
  /** Market data older than this many seconds is too old to act on. */
  maxDataAgeSeconds: 120,
  /** Reopen history is rebuilt at most this often. */
  historyRefreshHours: 6,
  /** The official calendar is re-read at most this often. */
  calendarRefreshHours: 24,
  /** How many order-book levels are read for the trust check. */
  bookLevels: 50,
  /** How many Bitget announcements are shown to the AI. */
  announcementsForAi: 5,
  /** The shadow ledger shares one market read between its loans for this many seconds. */
  shadowMarketShareSeconds: 20,
  /** The AI gets this many seconds to answer. A slow or failed answer becomes an alert, never an action. */
  modelTimeoutSeconds: 25,
} as const;

/**
 * "Check my loan" (public, no login, nothing stored). Product choices, not market data.
 * The borrowed coin is USDT, the coin Version 1 is built for (AGENTS.md section 1).
 */
export const CHECK_MY_LOAN = {
  loanCoin: "USDT",
  /** Requests allowed per visitor address per minute. Counts are kept in memory only, never the loan figures. */
  requestsPerMinute: 20,
  /** Largest amount accepted in either field. Rejects typing slips, not real loans. */
  maxAmount: 1_000_000_000_000,
} as const;

/** "Watch a weekend" (public, no login). Product choices. Results are kept in memory only, and never include anything typed by a visitor beyond the three loan numbers. */
export const WATCH_A_WEEKEND = {
  requestsPerMinute: 6,
  /** A past weekend does not change, so one answer is reused this long. */
  cacheMinutes: 30,
  /** The replay runs Morrow's real check once per this many minutes of the weekend. */
  stepMinutes: 30,
  /** Hours of price shown either side of the closure on the chart. */
  chartHoursAround: 6,
} as const;

/**
 * Default trigger distance in points from the margin-call level.
 * Chosen on the earlier period of the history replay (docs/METHOD.md); the user can change it in Settings.
 */
export const DEFAULT_TRIGGER_BUFFER_POINTS = 5;

/**
 * Loan size bands for public pages, in the borrowed coin (USDT), so exact balances are never published.
 * Presentation choice from AGENTS.md section 6. The last band has no upper limit.
 */
export const LOAN_SIZE_BANDS: ReadonlyArray<{ below: number; label: string }> = [
  { below: 1_000, label: "under 1,000 USDT" },
  { below: 5_000, label: "1,000 to 5,000 USDT" },
  { below: 25_000, label: "5,000 to 25,000 USDT" },
  { below: 100_000, label: "25,000 to 100,000 USDT" },
  { below: Number.POSITIVE_INFINITY, label: "over 100,000 USDT" },
];
